name: Publish 🚀

on:
  workflow_dispatch:
  push:
    branches:
    - master
    
env:
  AZURE_WEBAPP_NAME: api-jose-sanchez-gh
  AZURE_WEBAPP_PACKAGE_PATH: "./publish"
  
jobs:
  publish:
    runs-on: ubunto-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup .NET
        uses: action/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
        
      - name: Restore
        run: donet restore ./JSanchez_GH_Api.sln
        
      - name: Build
        run: dotnet build ./JSanchez_GH_Api.sln --configuration Release --no-restore
        
      - name: Publish
        run: dotnet publish ./JSanchez_GH_Api.sln --configuration Release --no-build --output '${{ env.AZURE_WEBAPP_PACKAGE_PATH }}' 
        
      - name: Deployment
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_PUBLISH_PROFILE }}
          package: "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"
  
